### ISSUE TITLE
Database models & serializers implementation

### ISSUE THREAD

**Issue by Sipos-Lucas-George** [Wifi-G9/backend#18]
Take another look at the database, I modified so it works and i did the migrations but there is an issue the DeveloperMessage, and please modify the .py files which contain UpperCaseCamelCase, switch it to underline and all lower case letters, preferable to be a short description 2-3 words. The only UpperCaseCamelCase should be the name of the class and everything else should be snake_case, fun fact Python's naming convention it's all about snake_case because python's a snake, keep that in mind.
If there is an issue with naming convetions take a look at this link: https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html
Or just have a look at the code I've written. HMU for other questions

**Comment by sergiusicoe** [comment]
Done
