### ISSUE TITLE
Search history tables

### ISSUE THREAD

**Issue by bia1708** [Wifi-G9/backend#19]
Implement the following:

- A table called **`Word_History`**:
  - This table will contain all the words searched by all the users with an added field: `timestamp`
  - This table will be _recycled_ once every month, but leave the most recent week as a buffer:
    - Example: Today is the 1st of November. On the 31st of October the procedure that cleans the database removed all searches with a timestamp that is earlier than the 24th of October (one full week of data is needed for calculating word of the day).
  - This table will have an associated procedure, **`generate_word_of_the_day`**, that calculates 'Word of the Day', based on the previous week, like this:
    - The procedure will be run every day, at 00:00.
    - The procedure will generate the most searched word across the last 7 days.
    - The procedure will insert said word in the 'Word of the Day' table.
      - Example:  Today is Monday, 6th November, 00:00. The implemented procedure will take all the words with a timestamp between Monday, 30th October, 00:01 and Sunday, 5th November, 11:59 and calculate what was the most searched word in this timeframe. This will become the 'Word of the Day' for Monday, 6th November. This word is inserted at the end of the **`Word_of_the_Day`** table.

- A table called **`Word_of_the_Day`**:
  - This table will contain all the most searched words per day.
  - Each entry will have an additional field, the `timestamp`.
  - Words will be inserted into this table automatically, every day at 00:00 when the **`generate_word_of_the_day`** procedure is called. 
  - The end goal for this table is to keep a history of the most searched words throughout the year and offer us a statistic at the end of the year (and also be recycled on January 1st, 00:00), but these functionalities are not required for now (I mean everything under this singular bullet point, not the entire table).

**Comment by Sipos-Lucas-George** [comment]
> - A table called Word_of_the_Day: 
>    - Each entry will have an additional field, the `timestamp`. 

Why do we need the `timestamp` field? I mean is not necessary in my opinion.

**Comment by bia1708** [comment]
@Sipos-Lucas-George you're right, we don't really need it for that table.

**Comment by sergiusicoe** [comment]
I finished creating the tables and procs but I can't create those automatic procs calls, Azure limits me.
