### ISSUE TITLE
Implement ChatGPT description class view

### ISSUE THREAD

**Issue by Sipos-Lucas-George** [Wifi-G9/backend#21]
1. Create a class view that calls the ChatGPT API:
[`Link to ChatGPT API`](https://platform.openai.com/docs/guides/text-generation/chat-completions-api)

2. The class should call the API with a prompt like:
`Describe the $word in a sentence`, make sure it doesn't return a more than 100 characters

3. After that add it in aggregated_data as an key, value pair in the dictionary:
`"description": "<result>"`

**Comment by bia1708** [comment]
For requirement 2, I think it should be mentioned that the answer shouldn't just be concatenated to fit into 100 characters, i.e. make sure you don't leave any unfinished sentences.

**Comment by Sipos-Lucas-George** [comment]
I mean I didn't want to mention it because it was pretty obvious, but now that you said it I am gonna mention that the prompt that I've provided was just an example, she could indeed just write a prompt that return under 100 characters such as:

`Describe the $word in maximum 100 words`

The idea remains the same, a little bit of tweaking and it should be perfect if it isn't right now.
