### ISSUE TITLE
Implement the PyTrends class view

### ISSUE THREAD

**Issue by Andrei-Fabian-Pop** [Wifi-G9/backend#22]
1. Create a class that interacts with the [PyTrends API](https://pypi.org/project/pytrends/) by receiving a word as request.
2. One should call the "interest over time" feature of the API and generate the data for 2 graphs, one for interest over the last month and the other with the interest over the last year.
3. 5 related topics with the searched word and 5 related trends

**Comment by bia1708** [comment]
Please document the data format that will be sent to the frontend (with comments).
