### ISSUE TITLE
Create Sentiment Analysis class view

### ISSUE THREAD

**Issue by Sipos-Lucas-George** [Wifi-G9/backend#23]
1. Create a class that calls the Sentiment Analysis API:
[`Sentiment Analysis API`](https://rapidapi.com/gaurmanojkumar530/api/text-analysis12)

2. The API should receive (for the first sprint) a text and return the sentiment analysis
`sentiment_analysis = SentimentAnalysis.as_view()(request, text)`

3. Added to aggregated_data as a key, value pair for the dictionary:
`"sentimental_analysis": sentiment_analysis`

**Comment by bia1708** [comment]
@Sipos-Lucas-George you missed a word inside requirement number 2.

**Comment by Sipos-Lucas-George** [comment]
Thank you @bia1708 :pray:
