### ISSUE TITLE
Add initial setup documentation

### ISSUE THREAD

**Issue by bia1708** [Wifi-G9/backend#25]
Document the steps required to set up the development environment in the repository `README.md`:

- How to install dependencies
- What to do with the `.env` file (maybe also have the file in the readme)
- How to connect to the database (also point to the database readme for driver install)
- Which files should not be modified
- How to access common accounts (+credentials)
- Anything else you think is important

**Comment by Sipos-Lucas-George** [comment]
I will never attach the .env to the project, the only reason we are using environment variables is to keep them protected :)))
