### ISSUE TITLE
Database Implementation

### ISSUE THREAD

**Issue by bia1708** [Wifi-G9/backend#9]
Implement the database for the project, following [the provided scheme](https://github.com/Wifi-G9/backend/tree/main/docs/database). 

- Implement procedures/functions for retrieving the data from the database (a sort of `getAll()` for every table, for now)
- Document the entities and functions that you have in the database in a readme.md that you can publish at this location: https://github.com/Wifi-G9/backend/tree/main/docs/database

My strong recommendation is that you implement the database in PostgreSQL, since it is cross-platform (Microsoft has its own methods and style).

**Comment by sergiusicoe** [comment]
I will use Microsoft Azure SQL because it is a solution that involves minimal costs for creating a cloud database.
